apiVersion: v1
kind: ServiceAccount
metadata:
  name: leader-election-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: leader-election-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "pods", "configmaps"]
    verbs: ["get", "watch", "list", "create", "update", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "watch", "list", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: leader-election-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: leader-election-sa
    namespace: default
roleRef:
  kind: Role
  name: leader-election-role
  apiGroup: rbac.authorization.k8s.io
